<a href="https://colab.research.google.com/github/tu25002-4828-alt/EU_M_Math-Repository/blob/main/Chap05_Ex01_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [3]:
#サンプルコード
sample_array = np.arange(10)
print('sample_array：', sample_array)

#前から数字を5つ取得して，sample_array_sliceに入れる
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

sample_array： [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [4]:
#サンプルコード
# sample_array_slice の3文字目までは，10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)

# スライスの変更はオリジナルのリストの要素も変更されていることに注意
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [5]:
#サンプルコード
#コピーして別のオブジェクトを作成

sample_array_copy = np.copy(sample_array)
print('コピーされたリスト：', sample_array_copy)

sample_array_copy[0:3] = 20
print('コピーを編集したリスト：', sample_array_copy)

#もとのリスト
print('もとのリスト：', sample_array)

コピーされたリスト： [10 10 10  3  4  5  6  7  8  9]
コピーを編集したリスト： [20 20 20  3  4  5  6  7  8  9]
もとのリスト： [10 10 10  3  4  5  6  7  8  9]


In [6]:
#サンプルコード
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [7]:
#サンプルコード
sample_names == 'a'

array([ True, False, False, False,  True])

In [8]:
#サンプルコード
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [9]:
#サンプルコード
cond_data = np.array([True, True, False, False, True])

x_array = np.array([1, 2, 3, 4, 5])
y_array = np.array([100, 200, 300, 400, 500])

print(np.where(cond_data, x_array, y_array))

[  1   2 300 400   5]


In [10]:
#サンプルコード
cond_data = np.array([True, True, False, False, True])
print(cond_data)

#重複削除
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [11]:
#サンプルコード
#ユニバーサル関数
sample_data = np.arange(10)
print('元のデータ：', sample_data)
print('すべての要素の平方根：', np.sqrt(sample_data))
print('すべての要素のネイピア関数：', np.exp(sample_data))

元のデータ： [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根： [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア関数： [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [12]:
#サンプルコード
#arangeで9つの要素を持つ配列を生成。reshapeで3行3列の行列に再形成

sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)
print('最小値：', sample_multi_array_data1.min)
print('最大値：', sample_multi_array_data1.max)
print('平均：', sample_multi_array_data1.mean)
print('合計：', sample_multi_array_data1.sum)

#行列を指定して合計値を求める
print('行の合計：', sample_multi_array_data1.sum(axis=1))
print('列の合計：', sample_multi_array_data1.sum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値： <built-in method min of numpy.ndarray object at 0x7a57dfffefd0>
最大値： <built-in method max of numpy.ndarray object at 0x7a57dfffefd0>
平均： <built-in method mean of numpy.ndarray object at 0x7a57dfffefd0>
合計： <built-in method sum of numpy.ndarray object at 0x7a57dfffefd0>
行の合計： [ 3 12 21]
列の合計： [ 3 12 21]


In [23]:
#サンプルコード
#真偽値の判定

cond_data = np.array([True,True,False,False,True])

print('Trueが少なくとも1つあるかどうか：', cond_data.any())
print('すべてTrueかどうか：',cond_data.all())

Trueが少なくとも1つあるかどうか： True
すべてTrueかどうか： False


In [25]:
#サンプルコード

sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('5より大きい数字はいくつあるか：', np.trace(sample_multi_array_data1))

print('対角成分：',np.diag(sample_multi_array_data1))
print('対角成分の和：',np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字はいくつあるか： 12
対角成分： [0 4 8]
対角成分の和： 12


In [36]:
#サンプルコード
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#サンプルコード
sample_array2 = sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
#サンプルコード
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
#サンプルコード
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

print(sample_array3)
print(sample_array4)

np.concatenate([sample_array3, sample_array4], axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
#サンプルコード
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

print(sample_array3)
print(sample_array4)

np.concatenate([sample_array3, sample_array4], axis=1)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [49]:
#サンプルコード
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

sample_array_vstack = np.vstack((sample_array3, sample_array4))
print(sample_array_vstack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
#サンプルコード
first,second,third = np.split(sample_array_vstack,[1,3])
print(first)
print(second)
second[0]
print(third)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]


In [54]:
#サンプルコード
first,second,third = np.split(sample_array_vstack,[1,3])

second[0]

array([4, 5, 6])

In [56]:
#サンプルコード
sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])
sample_array_vstack2 = np.vstack((sample_array3, sample_array4, sample_array5))
print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [59]:
#サンプルコード
first,second,third,forth = np.split(sample_array_vstack2,[2,3,5])
print('1つ目：\n',first,'\n')
print('2つ目：\n',second,'\n')
print('3つ目：\n',third,'\n')
print('4つ目：\n',forth,'\n')

1つ目：
 [[1 2 3]
 [4 5 6]] 

2つ目：
 [[7 8 9]] 

3つ目：
 [[10 11 12]
 [13 14 15]] 

4つ目：
 [[16 17 18]
 [19 20 21]] 



In [60]:
#サンプルコード
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

In [61]:
#サンプルコード
sample_array = np.arange(10)
print(sample_array)

sample_array + 3

[0 1 2 3 4 5 6 7 8 9]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
#5-1
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

sample_names == 'b'
print("\n")

data[sample_names == 'b']

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]




array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [15]:
#5-2
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

sample_names != 'c'
print("\n")

data[sample_names != 'c']

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]




array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [16]:
#5-3
cond_data = np.array([False, False, True, True, False])

x_array = np.array([1, 2, 3, 4, 5])
y_array = np.array([6, 7, 8, 9, 10])

print(np.where(cond_data, x_array, y_array))

[ 6  7  3  4 10]


In [17]:
#5-4
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2

print('平方根を計算した行列：\n',np.sqrt(sample_multi_array_data2))

平方根を計算した行列：
 [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [18]:
#5-5
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2

print('最大値を計算した行列：\n',np.sqrt(sample_multi_array_data2.max()))
print('最小値を計算した行列：\n',np.sqrt(sample_multi_array_data2.min()))
print('合計値を計算した行列：\n',np.sqrt(sample_multi_array_data2.sum()))
print('平均値を計算した行列：\n',np.sqrt(sample_multi_array_data2.mean()))

最大値を計算した行列：
 3.872983346207417
最小値を計算した行列：
 0.0
合計値を計算した行列：
 10.954451150103322
平均値を計算した行列：
 2.7386127875258306


In [19]:
#5-6
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2

print('対角成分の和：',np.trace(sample_multi_array_data2))

対角成分の和： 30


In [20]:
#5-7
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

print(sample_array1)
print(sample_array2)

print('結合：\n')
np.concatenate([sample_array1, sample_array2], axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
結合：



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
#5-8
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

print(sample_array1)
print(sample_array2)

print('結合：\n')
np.concatenate([sample_array1, sample_array2], axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
結合：



array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [77]:
#5-9
sample_list = [1,2,3,4,5]
sample_list + 3
#そのまま動かせば，エラーが起きる。「Numpyでは」暗黙的にコピーして大きさを揃えて全配列に3を足してくれる。
#NumPy配列に変換する必要がある。

TypeError: can only concatenate list (not "int") to list

In [78]:
#5-9
sample_list = [1,2,3,4,5]
sample_array = np.array(sample_list)
sample_array + 3
#リストをNumPy配列に変換してからブロードキャストを適用する

array([4, 5, 6, 7, 8])